services:
  - type: web
    name: Radhirra_Designs
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd Radhirra_Designs && uvicorn Radhirra_Designs.asgi:application --host 0.0.0.0 --port 8000"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
