services:
  - type: web
    name: Radhirra_Designs
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd Radhirra_Designs && gunicorn Radhirra_Designs.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
